#! /bin/bash

echo "This is now deprecated, things are handled directly with authorized_keys"
exit 1

KEYS_DIR=~/.ssh/all_authorized_keys

mv ~/.ssh/authorized_keys ~/.ssh/authorized_keys.bak

for f in `ls $KEYS_DIR`
do
	cat $KEYS_DIR/$f >> ~/.ssh/authorized_keys
done


#EOF
