#! /bin/bash
# set PATH so it includes user's private bin if it exists
if [ -d ~/bin ] ; then
    PATH=~/bin:"${PATH}"
fi

if [ -d ~/lib ] ; then 
    LD_LIBRARY_PATH=~/lib:"${LD_LIBRARY_PATH}"
fi 

export EDITOR=vim

export PERL5LIB=~/lib:"${PER5LIB}"

export TEXINPUTS=~/lib/latex//:"${TEXINPUTS}"

export PYTHONSTARTUP=~/.pythonrc

export PYTHONPATH=~/lib/python:~/a9engine/conf:$PYTHONPATH

# virtualenvwrapper stuff
export WORKON_HOME=~/envs
if [ ! -d $WORKON_HOME ] ; then 
	mkdir $WORKON_HOME
fi
if [ -e /usr/local/bin/virtualenvwrapper.sh ] ; then
	. /usr/local/bin/virtualenvwrapper.sh
fi

export TERMCOLOR=1

export ANSIBLE_NOCOWS=1

export SLOOT_FLASK_PATH=/home/sam/sloot/sloot.flask
export CAMASA_PATH=/home/sam/camasa
export FXST_PATH=/home/sam/fxst

# don't keep jrnl entries in bash history
export HISTIGNORE="$HISTIGNORE:jrnl *"

#EOF
