# vim:ft=sh

alias dclock='dclock -seconds -miltime -bg "#131A2A" -fg "#97A8AF" -led_off "#131A2A" # -date "%A %d %B %Y"'
alias ll='ls -l'
alias pyclean='find . -type f -name "*.pyc" -exec rm {} \; -print -or -type f -name "*~" -exec rm {} \; -print'

#EOF
